### ISSUE TITLE
Last frame of animation appears to be cut short

### ISSUE THREAD

**Issue by ThimbleFire** [martinhodler/unity-aseprite-importer#12]
frame time is half its set value

**Comment by martinhodler** [comment]
thanks for your report. I'm going to fix this as soon as possible.

**Comment by ThimbleFire** [comment]
Awesome! Thank you. I am terribly sorry I didn't report more information in my original post, was in an awful hurry. I am very happy to hear its not just on my end. Thank you for making such an excellent importer.

**Comment by martinhodler** [comment]
should be fixed with the commit eb9c2a630a05f71a4bafa19ffa0f98450087da6e.
