### ISSUE TITLE
Loop Animation Option not being applied 

### ISSUE THREAD

**Issue by alexpennells** [martinhodler/unity-aseprite-importer#17]
**Describe the bug**
Toggling the loop option on an animation gets ignored. Toggle works ok, but when applying the value always resets to true for the created animation clip

**To Reproduce**
1. Import `.aseprite` file
2. Uncheck `Loop` in the Animation Options on a single animation 
3. Click `Apply`
4. View the created animation clip in the Project view. `Loop Time` is always set to true

**Expected behavior**
`Loop Time` should be set to false for the created animation clip

**Screenshots**
<img width="308" alt="Screen Shot 2019-11-19 at 8 09 56 PM" src="https://user-images.githubusercontent.com/5923164/69200266-a25eff00-0b08-11ea-977c-d73c03838f94.png">
<img width="320" alt="Screen Shot 2019-11-19 at 8 10 19 PM" src="https://user-images.githubusercontent.com/5923164/69200267-a25eff00-0b08-11ea-9714-07e5b1105144.png">

**Desktop (please complete the following information):**
 - MacOS Mojave 10.14.5
 - Unity 2019.2.12f1

**Comment by martinhodler** [comment]
The issue is fixed thanks to @CeejayZSmith

**Comment by Mohammed-A-S** [comment]
Hi there, can u till me how did u fix it?

i have the same problem
