### ISSUE TITLE
Project is incompatible with Unity Package Manager

### ISSUE THREAD

**Issue by CeejayZSmith** [martinhodler/unity-aseprite-importer#20]
The project can not be imported using the unity package manager as there are no meta files.

**Steps To Reproduce**
1. Add 
`"io.tinu.asepriteimporter": "https://github.com/martinhodler/unity-aseprite-importer.git#master"` 
to the dependecies in `UNITY_PROJECT_FOLDER\Packages\manifest.json`
2. Open the Unity Project
3. View the errors in the console
4. View that the importer does not work because of the missing files.

**Expected behavior**
No errors and the files should be visible under the Packages folder in the Unity project window.

**Screenshots**
![erroraseprite](https://user-images.githubusercontent.com/23058271/72936848-ef0cc380-3d5f-11ea-9a70-818fbd0a416a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2019.3.0f5

**Additional context**
I propose the .meta files be generated and added to the git repo. This would also help with version control, if users do not use the package manager, and using this importer between projects (as the references could be different).

**Comment by martinhodler** [comment]
Good point. I will commit the meta files as soon as possible. Thanks for your work!

**Comment by martinhodler** [comment]
fixed with the commit b472e5bf9bc6ab93a96cf763551a7a9fee31e547
