### ISSUE TITLE
Error in GetTextureFromCel (#16) May not have been fixed correctly.

### ISSUE THREAD

**Issue by STUDIOCRAFTapps** [martinhodler/unity-aseprite-importer#22]
I made a sprite is aseprite with some pixels that were out of the canvas, in the bottom left corner.
I wasn't able to import that sprite. 

Unity gives me the same error messages mentioned in this issue;
https://github.com/martinhodler/unity-aseprite-importer/issues/16

From what I've seen, the issue may have not been fixed correctly.
I think I've resolved the issue using the following code.

The current code (256, AseFile.cs)
`for(int y = 0; y < renderRectHeight; y++) {
    for(int x = 0; x < renderRectWidth; x++) {
        int celDataIndex = (y + celY) * cel.Width + (x + celX);
        int index = (renderRectHeight - 1 - (y)) * renderRectWidth + (x);

        // The celDataIndex is out of range when celX or celY is > 0.
        colors[index] = cel.RawPixelData[celDataIndex].GetColor();
    }
}`

My temporary patch
`for(int y = 0; y < renderRectHeight; y++) {
    for(int x = 0; x < renderRectWidth; x++) {
        // The cel can't be sampled out of bounds in case celX/celY + x/y is bigger than the cel size
        if((x + celX) >= cel.Width) {
            continue;
        }
        if((y + celY) >= cel.Height) {
            continue;
        }
        int celDataIndex = (y + celY) * cel.Width + (x + celX);
        int index = (renderRectHeight - 1 - (y)) * renderRectWidth + (x);

        colors[index] = cel.RawPixelData[celDataIndex].GetColor();
    }
}`

The file that causes the error:
[Player_Jump.zip](https://github.com/martinhodler/unity-aseprite-importer/files/4494587/Player_Jump.zip)

**Comment by martinhodler** [comment]
Thanks for the detailed post. I was able to fix the issue and reimplemented the pixelmapping.
