### ISSUE TITLE
Slice support

### ISSUE THREAD

**Issue by AlexDavies8** [martinhodler/unity-aseprite-importer#29]
It would be nice to have support for slices to be imported as separate sprites (with correct 9-slicing and pivots). Support for animation with this would also be cool (and allow for multiple animated sprites in one file). Animated tilesets could also be useful, but slightly less so.

**Comment by martinhodler** [comment]
Hi @AlexDavies8 
I'm currently working on the sprite-editor branch. Supporting 9-slicing can be done as you would with normal png files. The goal with the sprite-editor branch is to support Unity's own Sprite Editor Window as you were using png's.

Try the branch and let me know if this fits your needs.

**Comment by martinhodler** [comment]
The feature should work with the current version of 1.0.3 with both importer variants.

At least since the commit 3df716dd997b10561dd8f8670e2571ff542ca418.
