### ISSUE TITLE
Transparent color option

### ISSUE THREAD

**Issue by martinhodler** [martinhodler/unity-aseprite-importer#3]
If someone uses a background-color for transparency it should be possible to replace this color with transparent pixels.

**Comment by advra** [comment]
I finished this feature last nigh and did some testing. I will make a new pull request.

**Comment by antiNT2** [comment]
I think this issue can be closed now

**Comment by martinhodler** [comment]
Yes. The reason I left it open was because of a lot of refactoring in the sprite-editor branch which will support the default Sprite-Editor from Unity.
