### ISSUE TITLE
Issue importing layer opacity when using "Normal" blending mode.

### ISSUE THREAD

**Issue by PhilippCh** [martinhodler/unity-aseprite-importer#30]
**Describe the bug**
The importer doesn't seem to import any opacity/transparency data when importing an ASE file with semi-transparent layers set to "Normal" blending mode. Is this intended? The result is the sprite not displaying as seen in Aseprite but rather like an alpha-clipped sprite with either full or no transparency.

**Expected behavior**
I would expect any sprite edited with Aseprite to import with proper transparency values even when using the "Normal" blending mode.

Changing Texture2DBlender.Normal to the following seems to fix the issue, though I'm not sure what other problems this causes:

```csharp
//c.a = a.a + b.a * (1f - a.a);
c.a = a.a + b.a * opacity;
```

**Screenshots**
Image as seen in Aseprite:
![Anmerkung 2020-06-22 232256](https://user-images.githubusercontent.com/966567/85336796-90e73680-b4df-11ea-845a-5c740c02602b.png)

Imported with the default blending:
![Anmerkung 2020-06-22 232320](https://user-images.githubusercontent.com/966567/85336817-9b093500-b4df-11ea-969b-1e69db938239.png)

Imported with the adjusted blending:
![Anmerkung 2020-06-22 232351](https://user-images.githubusercontent.com/966567/85336822-9fcde900-b4df-11ea-8ccd-895234652c2d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2020.1

**Comment by martinhodler** [comment]
This looks like an issue. I fixed the error in the sprite-editor branch which is containing the next bigger update.

**Comment by martinhodler** [comment]
With the merge of the sprite-editor branch I merged the fix into the master. 814fd2126df7acc80517900d268d85cdc66df0fb
