### ISSUE TITLE
Support .aseprite file extension

### ISSUE THREAD

**Issue by SekretOne** [martinhodler/unity-aseprite-importer#32]
**Is your feature request related to a problem? Please describe.**
Seems like only `.ase` files are recognized for import. Asperite has since moved to using `.asperite` extension to avoid conflicts with some other file types that were already using it.

**Describe the solution you'd like**
Import recognizes .asperite files and imports the same way.

**Describe alternatives you've considered**
I guess grumping it up and just reminding myself to select the .ase extension.

**Additional context**
I think it's fairly self explanatory.  I imagine it would be a low effort change.

**Comment by martinhodler** [comment]
Both file-extensions are implemented. It seems that there is a different error with your file. Please open a new issue if this still not works. I tested the importer with both file extensions and it worked fine on my side.
The line @nailuj29gaming  mentioned is the only way to make the ScriptedImporter recognizing the given file-extension.
