### ISSUE TITLE
Forked project (Makes it editable)

### ISSUE THREAD

**Issue by mjshin82** [martinhodler/unity-aseprite-importer#36]
The 'unity-aseprite-importer' is a good plugin but it only generate not-editable sprites and animations.
So I made a forked project which genetate editable resources.
source code: https://github.com/mjshin82/unity-aseprite-importer

I was thinking 'Pull request' to your project, but it has too many changes and not compatible with the origin.
So I just write this article here. Maybe this plugin could be improved with my approaches someday.

## Difference with the origin Aseprite-Importer
* It makes a sprite sheet file (not dynamic)
* You can edit the meta like custom physics shapes with the 'Sprite Editor'
* It generates tilemap with extended-padding, it solves lines tearing issue between tiles.
* New tilemap name rule support (row-col) which makes you find a certain tile fast.
* It makes animation files (not dynamic)
* You can add the custom events to each animation
* It makes an animation controller
* Some features are removed (Transparent color, Tilemap empty behavior) 

![image](https://user-images.githubusercontent.com/22926212/100529665-2cb66480-322d-11eb-82fa-5729572a75d9.png)
![image](https://user-images.githubusercontent.com/22926212/100529680-57a0b880-322d-11eb-8e8a-e0b48ff0495b.png)
![image](https://user-images.githubusercontent.com/22926212/100529693-7e5eef00-322d-11eb-8d46-5c7e03e958ce.png)

**Comment by martinhodler** [comment]
Nice work! I didn't had the time to work on these features. In my sprite-editor branch are some of the features you were mentioning. Are you using the TextureGenerator? If yes it would be nice to set the import settings for it like unity does for images like png or jpeg.
I can add you as a contributor to be able to push changes directly to the project if this helps.
I have the same problem with my sprite-editor branch. I have to re-implement some of the features to be able to merge it on the master.

Do you have the time to integrate your solution?

**Comment by advra** [comment]
I tried achieving something like this earlier this year but ran into some issues with animation events accessing some of the properties which made them read-only. 

I had a similar feature where you could add events to each animation; however, upon saving an ase file, the autoloader would overwrite the properties in Unity. Does this have the same issue? If so it might be better to preserve them as dynamic for read-and-write back into the ase file.

**Comment by mjshin82** [comment]
@martinhodler 
I love to. If you make me a member of this project, then I'll integrate my code to the new feature branch.

@advra 
I didn't have a overwrite issue on the animation event after re-import. But the 'Loop' property which is one of the animation property was overwritten after re-import, so I made recovery logic. And there is a similar issue in 'Custom Physics Shape' for the sprites, I also made recovery logic for that.

And also there are some improvements.
* Animator override controller support
* Sprite Atlas support
![image](https://user-images.githubusercontent.com/22926212/101280764-4861d200-380e-11eb-91f5-4b29dfd8764f.png)
![image](https://user-images.githubusercontent.com/22926212/101280779-557ec100-380e-11eb-9005-d11f34e47e9e.png)

**Comment by erlioniel** [comment]
I think it is for sure worth to merge the fork somehow. I guess that the approach is more or less the same and the biggest problem is a huge diff, right?

From my perspective, it's more beneficial to merge repos or deprecate one of them. Otherwise, we will split the community (which is not huge at all)

**Comment by martinhodler** [comment]
@erlioniel for sure.
I will merge the fork from @mjshin82 and integrate my changes afterwards. The problem for a short amount of time will be the wrong references in existing projects...

**Comment by erlioniel** [comment]
Sure, not saying that it's easy to do. However, I'm not sure that it's a good idea to close the issue before that :)

**Comment by martinhodler** [comment]
@erlioniel thanks for your opinion but I closed it in the second I merged the forked repo. It is integrated with the sprite-editor version (now called Bundled in the Editor). Because I prefer to have a simple and more integrated importer without creating a lot of files and assets i will focus on the Bundled importer.

**Comment by mjshin82** [comment]
Thanks for the integration
