### ISSUE TITLE
Support for OpenUPM

### ISSUE THREAD

**Issue by erlioniel** [martinhodler/unity-aseprite-importer#45]
Hi @martinhodler,

Can we ask to create some tags and support versioning for the importer? You have `package.json` with the metadata needed for creating a UPM package, but there are no tags.

OpenUPM is scanning (as far as I understood) this repo, but it didn't find any tags to create a package to release.

https://openupm.com/packages/io.tinu.asepriteimporter/

Thanks in advance.

**Comment by martinhodler** [comment]
Hi @erlioniel,
yes, for sure! Thanks for your input. I will create a release tag for the current version.

**Comment by martinhodler** [comment]
I testet it through the .unityasset download and the CLI both worked.

**Comment by erlioniel** [comment]
Thank you, @martinhodler!

I think the information on how to import it using UPM also can be useful for newcomers and you could add it to the README.md, but for sure that's optional. Thank you for tagging the release :)

Closing the issue.

**Comment by martinhodler** [comment]
@erlioniel That's a good point. I will add the information to the install section in the README.md. Thank you.

**Comment by erlioniel** [comment]
I'll reopen the issue since looks like there is some issue in the package configuration not allow to use it with UPM. Will update the issue with details when will have time to reproduce it in an isolated environment and dig futher.

**Comment by martinhodler** [comment]
The package.json was missing the dependency to com.unity.2d.sprite. The issue didn't occur on my side because I tested it with a 2D project setup which autmatically adds the dependency.
The dependency was added with the instructions to install the package with OpenUPM.

**Comment by erlioniel** [comment]
Okay, I think my issue is related to a problem with migrating to the newest version of the importer. Looks like the metadata of my version is incompatible with it. I'll investigate further and will create a new issue if there will be some reason to do that.

Thank you again, @martinhodler :) Closing the issue

**Comment by erlioniel** [comment]
Okay, after spending an additional hour I created a new issue (#46), hope it will help to make the project better (will try to contribute, if have enough time for that).

However, @martinhodler, would you be so kind to go and retrospectively add tags for version 1.0.0 - 1.0.3? And as well I guess it will be good to have a note in CHANGELOG.md that version 1.0.2 is not compatible with meta files generated by 1.0.0-1.0.1 & probably won't cover the same functionality?
