### ISSUE TITLE
Error CS0103 for Math in Editor/Aseprite/AseFile.cs

### ISSUE THREAD

**Issue by jkenny23** [martinhodler/unity-aseprite-importer#8]
Had to add "using System;" to the start of the file, because Math was not known to Unity. I'm using Unity 2018.3.12f1.

**Comment by martinhodler** [comment]
Strange... I wasn't able to reproduce the error with the current commit. Do you know which file caused the error?

**Comment by jkenny23** [comment]
Yes, it was "Editor/Aseprite/AseFile.cs".

**Comment by martinhodler** [comment]
Fixed in 895101b9d367a35298815d2abece531c1d5f91a3. Thank you for the report.
